### ISSUE TITLE
Dart frog support Isolates ?

### ISSUE THREAD

**Issue by vimptech-git** [VeryGoodOpenSource/dart_frog#1190]

**Comment by MarkOSullivan94** [comment]
If it does, it'd be great to see an example of how it works.

**Comment by tomarra** [comment]
Hi @vimptech-git 👋 Thanks for opening this issue.

Overall there shouldn't be anything specific or special that is needed in order to use Isolates with Dart Frog. While we don't have examples on our documentation site, if you have done some work with this and would like to contribute it back in the form of documentation it would be awesome to open a PR with the changes so we can get them reviewed. Until then closing this out as "won't fix".
