### ISSUE TITLE
feat: add Response.unknown() constructor

### ISSUE THREAD

**Issue by mtwichel** [VeryGoodOpenSource/dart_frog#131]
**Description**

Currently, if a request is sent and it does not match a route, it returns a `404` route with a body of `Route not found`. 

Since (for now), it seems `dart_frog` won't support specifying request methods in the builder (judging from #57), we manually should return the `404` route in the handler. It would be **super helpful** to have a response constructor to handle this case.

For syntax, I'm thinking
- Call it `Response.unknown()` following from `Response.json()` and `Response.bytes()`
- Have it automatically have a status code of `404`, and a body the same as when no route is detected.

Not a necessity, but in my experience with `dart_frog` so far, it would be really nice to have.

**Additional Thoughts**
Out of scope for this issue, but should adding the option for a custom `404` response be a good idea? Maybe a top level file named `_404.dart`? If people are excited about it, let's make another issue 💙

**Comment by felangel** [comment]
Hi @mtwichel 👋
Thanks for opening an issue!

Can you provide more context regarding when you’d want to manually return a 404? In my experience you more frequently end up returning 405 (method not allowed). I’m planning to revisit #57 with a different proposal because I think there are some other approaches to consider.

I’d prefer not to add names constructors that are tied to a statusCode because they don’t align with the .bytes and .json constructors (you’d have to manually specify content type headers and encode the body just to save writing the statusCode).

I do think the idea of having a way to configure the global 404 handler is a good idea and I’ll add that to the roadmap 👍

Thanks again and let me know what you think! 💙

**Comment by mtwichel** [comment]
> Can you provide more context regarding when you’d want to manually return a 404? In my experience you more frequently end up returning 405 (method not allowed).

You learn something new every day - I did not know that status code existed.

> I’d prefer not to add names constructors that are tied to a statusCode because they don’t align with the .bytes and .json constructors (you’d have to manually specify content type headers and encode the body just to save writing the statusCode).

That makes a lot of sense and something I hadn't considered. 

> I do think the idea of having a way to configure the global 404 handler is a good idea and I’ll add that to the roadmap 👍

That's awesome!

Thanks for your detailed response! Your reasoning makes total sense to me, and I'm going to close this issue.

I would love to pick your brain about #57 some time if you think I'd be valuable because I have some thoughts, especially as it relates to client generation and documentation generation.

Thanks for everything! 💙
