### ISSUE TITLE
feat: Flutter integration

### ISSUE THREAD

**Issue by pstromberg98** [VeryGoodOpenSource/dart_frog#169]
**Description**

This isn't so much a precise feature request as much as it is clarity and discussion on any Flutter integration plans. Remix and NextJS are both mentioned as being inspiration for Dart Frog which sparked some questions. Both Remix and NextJS are more than just a minimal backend framework. They are very opinionated frameworks around React and provide robust SSR and SSG features (among other things). That begs the question, how closely tied to Flutter will Dart Frog become long term? Will Dart Frog stay as an agnostic backend server (like express) or will it transform into something resembling NextJS/Remix but for Flutter?

It's worth mentioning that I am not vouching either way but am more curious on the maintainer's thoughts.

**Comment by felangel** [comment]
Hey @pstromberg98 👋 

Sorry for the really long delay! At the moment, Dart Frog's focus is on being a minimal backend framework. That may change in the future but I'd love to see how far we can get on the current trajectory with the help of community packages to enhance the tooling. For example, SSR and SSG should, in theory, be possible to implement on top of the existing tooling as packages. This is nice because it would allow developers to choose what dependencies they want and only pull in what is absolutely needed for their use cases.

Hope that helps!

Closing for now but feel free to comment with any additional thoughts/questions and I'm happy to continue the discussion 😄
