### ISSUE TITLE
feat: Redirect to a url

### ISSUE THREAD

**Issue by ekokurniadi** [VeryGoodOpenSource/dart_frog#347]
**Description**

can i redirect to a url when displaying html page, like redirect to dashboard page after login

**Requirements**

- [ ] Checklist of requirements to be fulfilled

**Additional Context**

Add any other context or screenshots about the feature request go here.

**Comment by felangel** [comment]
Hi @ekokurniadi 👋 
Thanks for opening an issue!

Yeah you should be able to perform redirects. Can you provide an example of what you've tried and the problems you're facing? Thanks!

**Comment by ekokurniadi** [comment]
such as when the user successfully logs in and when pressing the back button the page does not return to the login page

**Comment by felangel** [comment]
> such as when the user successfully logs in and when pressing the back button the page does not return to the login page, maybe like a navigator.pushReplacement or navigator.push on flutter

Dart frog should support session-based redirects using `middleware`. You can read more about `middleware` in [the docs](https://dartfrog.vgv.dev/docs/basics/middleware).

Closing for now since there are no actionable next steps for us. If you're still having trouble please provide a link to a minimal reproduction sample with more details regarding what you've tried and the issues you've encountered? Thanks!

**Comment by easazade** [comment]
I can add a middleware for session support. something that can be added to the pipeline like `requestLogger` middleware in dart_frog that currently exists. 

With an abstraction for persisting session data (session storage), So anyone can implement his/her own session storage implementation. I'd probably add a default in-memory session storage. I think that how its done in express.

Is that a contribution you would be interested in?
