### ISSUE TITLE
feat: Custom DockerFile on build

### ISSUE THREAD

**Issue by 4rthurmonteiro** [VeryGoodOpenSource/dart_frog#426]
**Description**

As a developer I want to make it possible to customize the DockerFile in the build.

Example:

I want to use a package from a private repository and I need to pass the permissions to the DockerFile.

**Comment by felangel** [comment]
Hi @4rthurmonteiro 👋 
Thanks for opening an issue!

This is on our roadmap and should be supported soon. Currently the plan was to use the Dockerfile at the project root if one exists instead of automatically generating one. It sounds like that should address your use case but let me know if you have any concerns, thanks!

**Comment by 4rthurmonteiro** [comment]
Exactly! @felangel 

As I can't use local external packages, I solved the problem by getting them straight from the repository via git in pubspec. But at the time of deployment, this permission problem arises.
