### ISSUE TITLE
build: 

### ISSUE THREAD

**Issue by SaiZayarHtet7** [VeryGoodOpenSource/dart_frog#497]
How about pagination on this dart frog will be work ? fully customized or  provide package ?.

**Comment by felangel** [comment]
Hi @SaiZayarHtet7 👋
Thanks for opening an issue!

Pagination is something that isn’t built into Dart Frog because it is straightforward to implement and isn’t a core piece of functionality. You can refer to the [Flutter News Toolkit](https://github.com/flutter/news_toolkit/blob/8ddef9776b82901e5cac138f70d1711e2e50f9b3/flutter_news_example/api/routes/api/v1/feed/index.dart#L19) for some examples of how pagination can be implemented. Hope that helps 👍
