### ISSUE TITLE
docs: configuring CORS with Dart Frog

### ISSUE THREAD

**Issue by felangel** [VeryGoodOpenSource/dart_frog#524]
**Description**

As a developer, I want to have documentation outlining how to configure CORS headers.

One concrete use case is developing a Flutter Web application locally and integrating with a Dart Frog server.

**Comment by KyleFin** [comment]
I'd actually invert this request:  `Create docs for local Flutter + Dart Frog development and include any helpful tips (like adding CORS headers for local Flutter web development)`

It seems good that current docs and examples focus on Dart Frog solely as a Dart server (independent of Flutter), but since one of Dart Frog's core value propositions is making it easy for Flutter developers to use familiar language, tools (hot reload), skills, and patterns (RequestContext == BuildContext) in Flutter AND server development, it might be good to have a simple codelab and/or tips for quickly getting set up to run a Dart Frog server locally AND interact with it from a local Flutter app.

As an inexperienced web developer, I ran an example Dart Frog server with `dart_frog dev` then launched a sample Flutter app with [`http`](https://pub.dev/packages/http) and [`dio`](https://pub.dev/packages/dio) using `flutter run` and tried to send requests to the server.

**_Because I didn't specify a target platform, my `flutter run` in VS Code terminal defaulted to web._**

I could see that the server was receiving requests, but the Flutter app didn't seem to receive any response. Even though I've dealt with CORS and sandboxing (like `com.apple.security.app-sandbox` and `com.apple.security.network.server` in `DebugProfile.entitlements` for iOS/MacOS), I still don't fully understand them, and it took me a while to track down the CORS issue. I was debugging and adding print statements to understand where requests were getting stuck. When I started to suspect CORS, in Google searches I wasn't sure if I needed to fix the issue on the server side or in the Flutter app configuration. I tried building the Flutter app for iOS simulator and it worked great.

After Felix [suggested](https://github.com/VeryGoodOpenSource/dart_frog/pull/523#issuecomment-1423447291) shelf_cors_headers, I was able to quickly resolve the issue for Flutter web, but I was only interested in CORS inasmuch as it was a blocker to my local development. I didn't need thorough documentation about configuring CORS. I just needed some help getting a simple example app running so I could play around with Flutter + Dart Frog. Just a warning to not use web or to add CORS would've been enough in my case.

I don't know if the way I used shelf_cors_headers to quickly unblock myself is "good" (is it discouraged to directly import shelf middleware in _middleware.dart?)

```
Handler middleware(Handler handler) {
  return handler.use(requestLogger()).use(fromShelfMiddleware(corsHeaders()));
}
```

but **CORS also turned out to be helpful as I'm learning Dart Frog to play with an example of how I could add and chain shelf middleware.**
