### ISSUE TITLE
docs: how to create a package with dartfrog?

### ISSUE THREAD

**Issue by abcnow** [VeryGoodOpenSource/dart_frog#667]
Hi There: I am trying to create a package within a project with dartfrog but I can't find any document about it.. with flutter you just enter "flutter create --template=package my_cool_package" and it creates a package within your project.. I tried "dart_frog create --template=package my_cool_package" but nothing happened.. your help is much appreciated!

**Comment by AndreXi** [comment]
Hi, you can find it here https://dartfrog.vgv.dev/docs/overview

If you have `dart_frog` the terminal will tell you the following because **template** option does not exist.
```
> dart_frog create --template=package my_cool_package
Could not find an option named "template".

Usage: dart_frog create [arguments]
-h, --help            Print this usage information.
    --project-name    The project name for this new project. This must be a valid dart package name.

Run "dart_frog help" to see global options.
```

I think the terminal is telling you that `dart_frog` command is not found. Be sure you installed it and have the dart global bin folder in your path. 

To install it run:
```sh
dart pub global activate dart_frog_cli
```
And pay attention if dart tells you if **the pub executables are not in you path**. In this case dart will provide you the command to add it in you path.

**Comment by erickzanardo** [comment]
@abcnow, the `dart_frog` cli can only create a dart frog project and dart frog related templates.

To create an internal package within your dart frog project from the command line, you just need to create a simple dart package, which can be done via the dart cli: `dart create -t package`, or you could also use very_good_cli: `very_good create dart_package`.

**Comment by erickzanardo** [comment]
Closing this given the answers to the question provided above. In case you still have doubts, please feel free to add new comments here and we can reopen if needed.
