### ISSUE TITLE
feat: ORM

### ISSUE THREAD

**Issue by benyaminbeyzaie** [VeryGoodOpenSource/dart_frog#85]
I think ORM and documentation for connecting the app to a database would be helpful!

**Comment by mtwichel** [comment]
Just my two cents - while I agree an ORM would be awesome for the dart community, I would personally love that as a separate project than dart frog. What I appreciate about Dart Frog is its simplicity and focus, and I worry adding an ORM would be too much imo.

Plus, there are a few projects that accomplish having an http server with an integrated database and ORM. The main one that comes to mind is [Serverpod](https://serverpod.dev/), which is a great platform if you're using Flutter!

**Comment by benyaminbeyzaie** [comment]
What is dart frog exact use case without connecting to a database? I mean as a back-end framework database is necessary. Can you share some useful projects developed by dart frog? I think I'm missing the point of the project.
Thanks.

**Comment by felangel** [comment]
> What is dart frog exact use case without connecting to a database? I mean as a back-end framework database is necessary. Can you share some useful projects developed by dart frog? I think I'm missing the point of the project.
> Thanks.

As stated in the README:

> The goal of Dart Frog is to help developers effectively build backends in Dart. Currently, Dart Frog is focused on optimizing the process of building backends which aggregate, compose, and normalize data from multiple sources.

Dart Frog is still experimental so there are no production-ready projects build with Dart Frog but just because Dart Frog doesn’t ship with an ORM doesn’t mean you can’t connect to a database. Check out https://github.com/darjaorlova/bunny_search_api_frog_experimental/blob/9a024d5c7773ae0cc7aaaec35a048dbc98c0b6d0/database/connection.dart#L14 as an example.

In addition, as @mtwichel mentioned, the goal of dart_frog is to provide a lightweight core. ORM support should be something that ideally can be added as a dependency (like prisma) but is not required or part of the core library because in some cases you might just want to aggregate/compose data from multiple sources.

Hope that helps 👍

**Comment by benyaminbeyzaie** [comment]
Thanks for all the answers, You guys are the best!
I'm closing the issue.
