### ISSUE TITLE
feat: Custom Host IP

### ISSUE THREAD

**Issue by KunjKanani** [VeryGoodOpenSource/dart_frog#912]
**Description**

I wanted to run the server on 0.0.0.0. So, I can connect physical devices to the backend via the WIFI/LAN network. 

**Requirements**

- [ ] --host support in dart_frog_cli.

**Comment by KunjKanani** [comment]
@alestiago I want to work on this feat. May I open PR?

**Comment by alestiago** [comment]
Thanks @KunjKanani for opening an issue! I will triage this with the team early next week and I will let you know about it, thank you so much!

**Comment by KunjKanani** [comment]
Hi @alestiago , Yes, I will raise a PR very soon. Please feel free to assign it to me.

**Comment by alestiago** [comment]
Hi @KunjKanani , I was revisiting this issue and noticed your main use-case was to connect physical devices to your Local Area Network. This should already be possible, instead of using "localhost"  try using your computer's host (in Mac, System Preferences > Network > WiFI and select "Your IP address") in addition to the port Dart Frog is using.

Besides this use-case, do you have any other use-case or is this simply a cosmetic change?
